[package]
name = "compiler"
version = "0.1.0"
authors = ["0918nobita <nobita.0918@gmail.com>"]
edition = "2018"

[dependencies]
once_cell = "1.5"
serde_json = "1.0"

[dependencies.clap]
version = "3.0.0-beta.2"
features = ["wrap_help"]

[dependencies.serde]
version = "1.0"
features = ["derive"]
